(()=>{'use strict';
const app=document.getElementById('app'),home=app.innerHTML;
const init=()=>({step:0,quote:{},answers:{},method:null,width:'',height:'',reference:'a4',confirmed:false,points:[],photos:[null,null],measurement:null,busy:false});
let state=init(),generation=0;
const refs={a4:{name:'A4用紙（おすすめ）',long:297},business:{name:'名刺（91 × 55㎜と確認済み）',long:91},card:{name:'無地のカード（85.6 × 54㎜と確認済み）',long:85.6}};
const choices={structure:[['wood','木造住宅です','プレハブ工法を除きます。工法が不明なら「わからない」でOK。'],['rc','鉄骨・鉄筋コンクリートです',''],['other','その他のつくりです','プレハブ工法など'],['unknown','わからない','']],floor:[['first','1階にあります',''],['upper','2階以上にあります',''],['unknown','わからない','']],condition:[['clear','気になる点はありません',''],['concern','ひび・雨じみなどが気になります',''],['unknown','わからない','']],space:[['clear','通りやすいです',''],['tight','少し狭い・物があります',''],['unknown','わからない','']]};
const labels={structure:'お住まい',floor:'玄関の位置',condition:'玄関まわり',space:'出入りのスペース'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const q=k=>`<div class="choices" role="group" aria-label="${labels[k]}">${choices[k].map(([v,t,s])=>`<button class="choice" data-answer="${k}" data-value="${v}" aria-pressed="${state.answers[k]===v}"><span>${t}${s?`<small>${s}</small>`:''}</span></button>`).join('')}</div>`;
const nav=(t='次へ')=>`<div class="nav"><button class="back" id="back">← 戻る</button><button class="primary" id="next">${t}<span>→</span></button></div>`;
const progress=()=>`<div class="progress"><span>STEP ${state.step+1} / 7</span><div class="track" role="progressbar" aria-label="チェックの進み具合" aria-valuemin="1" aria-valuemax="7" aria-valuenow="${state.step+1}"><i style="width:${(state.step+1)/7*100}%"></i></div><span>${state.step<4?'お住まいのこと':state.step<6?'大きさのこと':'チェック結果'}</span></div>`;
function valid(){const s=state.step,a=state.answers;return s===1?!!a.structure:s===2?!!a.floor:s===3?!!a.condition&&!!a.space:s===4?!!state.method:!state.busy;}
function updateNext(){const n=document.getElementById('next');if(n)n.disabled=!valid();}
let transitioning=false;
async function go(s){
 if(transitioning)return;
 transitioning=true;
 const previous=state.step,forward=s>previous;
 const motion=!window.matchMedia('(prefers-reduced-motion: reduce)').matches&&typeof app.animate==='function';
 generation++;state.busy=false;app.inert=true;
 try{
  if(motion)await app.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY('+ (forward?-16:16) +'px)'}],{duration:180,easing:'ease-in',fill:'forwards'}).finished;
  app.getAnimations().forEach(a=>a.cancel());
  state.step=s;render();window.scrollTo({top:0,behavior:'instant'});
  app.querySelector('h1,h2')?.setAttribute('tabindex','-1');
  app.querySelector('h1,h2')?.focus({preventScroll:true});
  if(motion){
   const nodes=s===0?[app.querySelector('.hero')]:[...app.children].filter(e=>!e.classList.contains('progress'));
   const animations=nodes.map((el,i)=>el.animate([{opacity:0,transform:'translateY('+ (forward?24:-18) +'px)'},{opacity:1,transform:'translateY(0)'}],{duration:560,delay:Math.min(i,5)*45,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'}));
   const bar=app.querySelector('.track i');if(bar)bar.animate([{width:(previous+1)/7*100+'%'},{width:(s+1)/7*100+'%'}],{duration:650,easing:'cubic-bezier(.16,1,.3,1)'});
   const token=generation;setTimeout(()=>{if(token===generation)app.inert=false;},150);
   await Promise.allSettled(animations.map(a=>a.finished));
  }
 }finally{app.inert=false;transitioning=false;app.querySelector('h1,h2')?.focus({preventScroll:true});}
}
function error(t){const el=document.getElementById('error');if(el)el.textContent=t;}
function render(){app.classList.toggle('is-home',state.step===0);if(!state.step){app.innerHTML=home;document.getElementById('start').onclick=()=>go(1);return;}let body='';
if(state.step===1)body=`<p class="eyebrow">QUESTION 01</p><h2 tabindex="-1">お住まいは<br>木造住宅ですか？</h2><p class="sub">わかる範囲で大丈夫です。</p>${q('structure')}<p class="hint">木造以外のお住まいも、つくりに合わせて確認します。</p>${nav()}`;
if(state.step===2)body=`<p class="eyebrow">QUESTION 02</p><h2 tabindex="-1">玄関は1階に<br>ありますか？</h2><p class="sub">おうちの階数ではなく、玄関のある位置を教えてください。</p>${q('floor')}<p class="hint">入口に数段の階段があっても、玄関が1階なら「1階」でOKです。</p>${nav()}`;
if(state.step===3)body=`<h2 tabindex="-1">いつもの玄関を、<br>少し思い浮かべて。</h2><section class="group"><p class="eyebrow">QUESTION 03</p><h3>玄関まわりの状態を教えてください</h3><p class="sub">枠や壁のひび、雨じみなど、見える範囲だけで大丈夫です。</p>${q('condition')}</section><section class="group"><p class="eyebrow">QUESTION 04</p><h3>玄関の内側・外側は、<br>人が通りやすいですか？</h3>${q('space')}</section>${nav('大きさの確認へ')}`;
if(state.step===4)body=`<h2 tabindex="-1">大きさは、<br>どう確認しますか？</h2><p class="sub">道具がなくても、チェックを続けられます。</p><div class="choices">${[['manual','メジャーで測る','幅と高さを入力。単位は㎜です。'],['photo','写真から目安を出す','A4用紙などと一緒に撮影。'],['skip','採寸せずに進む','大きさは現地調査におまかせ。']].map(([v,t,s])=>`<button class="choice" data-method="${v}" aria-pressed="${state.method===v}"><span>${t}<small>${s}</small></span></button>`).join('')}</div>${nav()}`;
if(state.step===5)body=measurementScreen();if(state.step===6)body=resultScreen();app.innerHTML=progress()+body;
app.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{state.answers[b.dataset.answer]=b.dataset.value;app.querySelectorAll(`[data-answer="${b.dataset.answer}"]`).forEach(x=>x.setAttribute('aria-pressed',x===b));updateNext();});
app.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{if(state.method!==b.dataset.method){state.measurement=null;state.points=[];state.confirmed=false;}state.method=b.dataset.method;app.querySelectorAll('[data-method]').forEach(x=>x.setAttribute('aria-pressed',x===b));updateNext();});
const back=document.getElementById('back');if(back)back.onclick=()=>go(state.step-1);const next=document.getElementById('next');if(next)next.onclick=()=>{if(!valid())return;if(state.step===5){try{state.measurement=state.method==='manual'?Doorimo.manual(state.width,state.height):state.method==='photo'?photoEstimate():null;}catch(e){error(e.message);return;}}go(state.step+1);};
if(state.step===5)bindMeasurement();if(state.step===6)DoorimoQuote.bind({answers:Object.keys(labels).map(k=>({label:labels[k],value:choices[k].find(x=>x[0]===state.answers[k])?.[1]||'未回答'})),measurement:state.measurement,result:Doorimo.assess(state.answers),photos:state.photos},state.quote);if(state.step===6)document.getElementById('restart').onclick=()=>{state=init();go(0);};updateNext();}
function upload(i,t){const p=state.photos[i];return `<label for="file${i}">${t}</label><div class="upload"><input id="file${i}" type="file" accept="image/*" capture="environment" aria-label="${t}"><p class="micro">撮影するか、保存済みの写真を選べます（20MBまで）。</p></div>${p?`<img class="photo" src="${p.url}" alt="${i===0?'玄関の正面':'気になる部分'}の選択した写真"><button class="smallbtn" data-remove="${i}">この写真を削除</button>`:''}`;}
function measurementScreen(){return `<h2 tabindex="-1">${state.method==='manual'?'玄関の大きさを、<br>ざっくりと。':state.method==='photo'?'正面から、<br>1枚撮ってみましょう。':'写真があれば、<br>相談がスムーズに。'}</h2><p class="sub">${state.method==='manual'?'ドアの扉ではなく、枠の内側の幅と高さを測ります。':'撮影・採寸はあとでも大丈夫です。'}</p><div class="guide"><svg viewBox="0 0 90 120" role="img" aria-label="枠全体を正面から撮る図"><rect x="16" y="7" width="58" height="99" fill="#d4b998" stroke="#496051" stroke-width="5"/><rect x="52" y="57" width="13" height="19" fill="white" stroke="#496051"/><path d="M22 110H68M9 15V98" stroke="#496051" stroke-width="2"/><path d="m25 107-4 3 4 3m40-6 4 3-4 3M6 19l3-5 3 5M6 95l3 5 3-5" fill="none" stroke="#496051"/></svg><p>枠全体が入るように、正面から。<br>足元に気をつけて撮影してください。</p></div>${state.method==='manual'?`<p class="unit-note">単位は㎜です。</p><div class="fields"><label>枠の内側の幅<input id="width" type="number" inputmode="decimal" min="200" max="6000" step="1" placeholder="例：900" value="${esc(state.width)}"></label><label>枠の内側の高さ<input id="height" type="number" inputmode="decimal" min="500" max="5000" step="1" placeholder="例：2000" value="${esc(state.height)}"></label></div><p class="micro">分からない部分は空欄でも構いません。</p>`:''}${state.method==='photo'?`<label for="reference">一緒に写すもの</label><select id="reference">${Object.entries(refs).map(([k,r])=>`<option value="${k}" ${state.reference===k?'selected':''}>${r.name}</option>`).join('')}</select><p class="hint">A4用紙を、測る枠と同じ奥行きの面にまっすぐ貼って、枠全体と一緒に撮影します。</p><p class="micro">名刺・カードはサイズをご確認ください。個人情報のないものを使います。</p>`:''}${upload(0,'正面の写真（任意・1枚）')}${state.method==='photo'&&state.photos[0]?`<label class="checkline"><input id="confirmed" type="checkbox" ${state.confirmed?'checked':''}>基準物のサイズが合っていて、枠と同じ奥行きにあり、正面から撮れています。</label><div id="point-section" ${state.confirmed?'':'hidden'}><p class="hint" id="point-instruction" aria-live="polite"></p><div class="measure-area"><canvas id="measure" role="img" aria-label="写真上で基準物の長辺2点、枠の幅2点、高さ2点を順にタップ"></canvas></div><button class="smallbtn" id="undo">1点戻す</button><button class="smallbtn" id="clear-points">点をすべて消す</button><p class="micro">写真の寸法は目安です。正確な採寸は現地で行います。</p><p id="estimate" class="hint" aria-live="polite"></p></div>`:''}<details><summary>気になる部分の写真をもう1枚追加する（任意）</summary>${upload(1,'気になる部分（追加1枚まで）')}</details><p class="micro">個人情報の保護に気を付けてください。<br>写真は送信されません。画面を閉じると消えます。</p><p id="error" class="error" role="alert"></p>${nav('結果を見る')}<button class="smallbtn" id="skip-measure">採寸を省略して結果へ</button>`;}
function photoEstimate(){if(!state.photos[0]||!state.confirmed||state.points.length===0)return null;if(state.points.length!==6)throw Error('6点すべてを指定するか、「採寸を省略して結果へ」を選んでください。');return Doorimo.estimate(state.points,refs[state.reference].long,state.photos[0].width,state.photos[0].height);}
function bindMeasurement(){['width','height'].forEach(k=>{const el=document.getElementById(k);if(el)el.oninput=()=>{state[k]=el.value;error('');};});const ref=document.getElementById('reference');if(ref)ref.onchange=()=>{state.reference=ref.value;state.points=[];state.measurement=null;state.confirmed=false;render();};document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{generation++;state.busy=false;const i=Number(b.dataset.remove);state.photos[i]=null;if(!i){state.points=[];state.measurement=null;state.confirmed=false;}render();});[0,1].forEach(i=>document.getElementById('file'+i).onchange=e=>loadPhoto(e.target.files[0],i));document.getElementById('skip-measure').onclick=()=>{state.measurement=null;go(6);};const confirmed=document.getElementById('confirmed');if(confirmed)confirmed.onchange=()=>{state.confirmed=confirmed.checked;if(!state.confirmed){state.points=[];state.measurement=null;}document.getElementById('point-section').hidden=!state.confirmed;draw();};const canvas=document.getElementById('measure');if(canvas){canvas.onclick=e=>{if(!state.confirmed||state.points.length===6)return;const r=canvas.getBoundingClientRect();state.points.push({x:(e.clientX-r.left)/r.width*canvas.width,y:(e.clientY-r.top)/r.height*canvas.height});draw();};document.getElementById('undo').onclick=()=>{state.points.pop();state.measurement=null;draw();};document.getElementById('clear-points').onclick=()=>{state.points=[];state.measurement=null;draw();};draw();}}
function loadPhoto(file,i){if(!file)return;if(file.size>20*1024*1024){error('写真は20MB以下のものを選んでください。');return;}if(!file.type.startsWith('image/')){error('画像ファイルを選んでください。');return;}const token=++generation;state.busy=true;updateNext();error('写真を読み込んでいます…');const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);if(token!==generation)return;try{const scale=Math.min(1,1600/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*scale);c.height=Math.round(img.naturalHeight*scale);if(!c.width||!c.height)throw Error();c.getContext('2d').drawImage(img,0,0,c.width,c.height);state.photos[i]={url:c.toDataURL('image/jpeg',.88),width:c.width,height:c.height,image:c};if(!i){state.points=[];state.measurement=null;state.confirmed=false;}state.busy=false;render();}catch{state.busy=false;updateNext();error('この写真を表示できませんでした。JPEGまたはPNGでお試しください。');}};img.onerror=()=>{URL.revokeObjectURL(url);if(token!==generation)return;state.busy=false;updateNext();error('この写真を表示できませんでした。JPEGまたはPNGでお試しください。');};img.src=url;}
function draw(){const c=document.getElementById('measure'),p=state.photos[0];if(!c||!p)return;c.width=p.width;c.height=p.height;const ctx=c.getContext('2d');ctx.drawImage(p.image,0,0);const radius=Math.max(8,c.width/70);state.points.forEach((p,i)=>{if(i%2){ctx.beginPath();ctx.moveTo(state.points[i-1].x,state.points[i-1].y);ctx.lineTo(p.x,p.y);ctx.lineWidth=radius/3;ctx.strokeStyle='#ffde77';ctx.stroke();}ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.fillStyle='#315b4c';ctx.fill();ctx.strokeStyle='white';ctx.lineWidth=radius/5;ctx.stroke();ctx.font=`bold ${radius*1.3}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='white';ctx.fillText(i+1,p.x,p.y);});const instructions=['基準物の「長い辺」の端をタップ','その長い辺の反対の端をタップ','測る枠の内側・左端をタップ','同じ高さの右端をタップ','測る枠の内側・上端をタップ','同じ縦の線上の下端をタップ'];document.getElementById('point-instruction').textContent=state.points.length<6?`${state.points.length+1} / 6　${instructions[state.points.length]}`:'6点を指定しました。位置を確認してください。';const e=document.getElementById('estimate');e.textContent='';error('');if(state.points.length===6){try{const m=photoEstimate();e.textContent=`単位は㎜です。 写真からの目安：幅 約${m.width}㎜ × 高さ 約${m.height}㎜（参考）`;}catch(err){error(err.message);}}}
function resultScreen(){const r=Doorimo.assess(state.answers),m=state.measurement;return `<div class="result-icon">${r.kind==='possible'?'⌂':'↗'}</div><p class="eyebrow">わが家のチェック結果</p><h2 tabindex="-1">${r.kind==='possible'?'交換できる<br>可能性があります':'詳しくは<br>現地調査が必要です'}</h2><p>${r.kind==='possible'?'玄関リフォームの第一歩が見えてきました。<br>詳しい条件を、専門スタッフと確認しましょう。':'お住まいに合わせた方法を、<br>専門スタッフと一緒に確認しましょう。'}</p>${r.reasons.length?`<div class="result-box"><h3>確認したいポイント</h3><ul>${r.reasons.map(x=>`<li>${x}</li>`).join('')}</ul></div>`:''}<div class="result-box"><h3>今回のメモ</h3>${Object.keys(labels).map(k=>`<p><small>${labels[k]}</small><br>${choices[k].find(x=>x[0]===state.answers[k])?.[1]||'未回答'}</p>`).join('')}<hr style="border:0;border-top:1px solid var(--line)"><p>${m?`${m.source==='photo'?'写真からの目安':'メジャーでの概寸'}<br><span class="unit-note">単位は㎜です。</span><br><strong>幅 ${m.width==null?'未記入':'約'+m.width+'㎜'} × 高さ ${m.height==null?'未記入':'約'+m.height+'㎜'}</strong>`:'大きさは現地で確認します'}</p><p class="micro">${m?'寸法は相談のための目安です。':''} 写真：${state.photos.filter(Boolean).length}枚</p></div><div class="hint"><strong>施工の可否は、現地調査で確認します。</strong><br>枠の材質・取付け方、床のつくり、傷み、正確な寸法、防火仕様など、写真や今回の質問だけでは確認できない条件があります。</div>${DoorimoQuote.form(state.quote)}<details><summary>このチェックの資料について</summary><p>YKK AP「ドアリモ 玄関・勝手口 現場調査マニュアル」2026年8月版、p.14・96–98・138をもとに簡略化しました。戸建て玄関ドアの検討入口であり、全商品・全条件の判定ではありません。写真の概寸は精度未検証の参考値です。このテスト版から相談や写真は送信されません。YKK APの公式診断サービスではありません。</p></details><div class="nav"><button id="back" class="back">← 入力へ戻る</button><button id="restart" class="primary">最初からやり直す<span>↻</span></button></div><p class="micro">やり直すと、回答・写真・測定点をすべて消します。</p>`;}
render();const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'read_doorimo_check',description:'Read the current simple door-remodel check without photos. Does not certify installation eligibility.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Empty object required');return {step:state.step+1,answers:{...state.answers},measurement:state.measurement,result:Doorimo.assess(state.answers)};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
