(()=>{'use strict';
const fields=[['shop','依頼先の施工店','text','例：〇〇リフォーム'],['name','お名前','text',''],['phone','電話番号','tel',''],['email','メールアドレス','email',''],['address','工事をご希望の住所','text',''],['timing','ご希望の時期','text','例：年内・まずは相談したい'],['request','ご希望・ご相談','textarea','例：断熱性を高めたい、明るい玄関にしたい']];
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paperCSS=`*{box-sizing:border-box}body{margin:0;color:#20352d;background:#fff;font:14px/1.7 -apple-system,BlinkMacSystemFont,"Yu Gothic",Meiryo,sans-serif}.quote-paper{max-width:800px;margin:0 auto;padding:42px}h1{font-size:27px;line-height:1.5;margin:0 0 10px}h2{font-size:17px;margin:26px 0 10px;border-bottom:2px solid #284d3e;padding-bottom:6px}p{margin:8px 0}.quote-meta{font-size:12px;color:#58625d}.quote-table{width:100%;border-collapse:collapse;table-layout:fixed}.quote-table th,.quote-table td{border:1px solid #d4dbd5;padding:9px 12px;text-align:left;vertical-align:top;white-space:pre-wrap;overflow-wrap:anywhere}.quote-table th{width:29%;font-weight:500;background:#f5f7f3}.quote-note{font-size:12px;margin-top:22px;border-top:1px solid #d4dbd5;padding-top:12px}li{overflow-wrap:anywhere}.quote-photo{break-inside:avoid;margin:24px 0}.quote-photo img{display:block;max-width:100%;max-height:220mm;object-fit:contain;margin:auto}.quote-photo figcaption{font-size:12px;margin-top:8px}.quote-photos{break-before:page}.quote-table tr{break-inside:avoid}@page{size:A4;margin:15mm}@media print{.quote-paper{padding:0;max-width:none}.quote-toolbar{display:none!important}}@media(max-width:600px){.quote-paper{padding:24px 18px}h1{font-size:23px}.quote-table th,.quote-table td{padding:8px;font-size:12px}}`;
function form(values={}){return `<section class="quote-builder"><p class="eyebrow">NEXT STEP</p><h3>見積もりの相談を、<br>ここから。</h3><p class="sub">今回のチェックを、施工店に渡せる依頼書にまとめます。</p><details id="quote-fields"><summary>見積もり依頼書を作る</summary><form id="quote-form"><p class="micro">分からない部分は空欄でも構いません。あとから手書きでも記入できます。</p>${fields.map(([k,label,type,placeholder])=>`<label for="quote-${k}">${label}</label>${type==='textarea'?`<textarea id="quote-${k}" name="${k}" rows="4" maxlength="2000" placeholder="${placeholder}">${escape(values[k])}</textarea>`:`<input id="quote-${k}" name="${k}" type="${type}" maxlength="300" placeholder="${placeholder}" value="${escape(values[k])}">`}`).join('')}<p class="micro">個人情報の保護に気を付けてください。<br>入力内容は送信されません。再読み込みすると消えます。</p><button class="primary" type="submit">依頼書を確認する <span>→</span></button></form></details></section>`;}
function paper(data,values,date=new Date()){
 const row=(label,value)=>`<tr><th scope="row">${escape(label)}</th><td>${escape(value||'未記入')}</td></tr>`;
 const m=data.measurement;
 return `<article class="quote-paper"><p class="quote-meta">玄関リフォームのご相談</p><h1>ドアリモ 見積もり依頼書</h1><p class="quote-meta">作成日：${escape(date.toLocaleDateString('ja-JP'))}</p><p>下記の内容について、現地調査とお見積もりをお願いします。</p><h2>ご依頼者・ご希望</h2><table class="quote-table"><tbody>${fields.map(([k,label])=>row(label,values[k])).join('')}</tbody></table><h2>玄関の簡易チェック</h2><table class="quote-table"><tbody>${data.answers.map(a=>row(a.label,a.value)).join('')}${row('簡易チェック結果',data.result.kind==='possible'?'交換できる可能性があります':'詳しくは現地調査が必要です')}${row('概寸（単位は㎜です。）',m?`${m.source==='photo'?'写真からの目安（精度未検証）':'メジャーでの概寸'}\n幅 ${m.width==null?'未記入':'約'+m.width+'㎜'} × 高さ ${m.height==null?'未記入':'約'+m.height+'㎜'}`:'未採寸・現地で確認')}${row('添付写真',data.photos.filter(Boolean).length+'枚')}</tbody></table>${data.result.reasons.length?`<h2>現地で確認したいこと</h2><ul>${data.result.reasons.map(r=>`<li>${escape(r)}</li>`).join('')}</ul>`:''}<p class="quote-note">本書はお見積もりの依頼用です。施工の可否・仕様・金額を確定するものではありません。概寸は参考値です。正確な寸法、取付け条件、防火仕様等は現地調査でご確認ください。<br>ドアリモ簡易チェックで作成（YKK APの公式診断サービスではありません）。</p>${data.photos.some(Boolean)?`<section class="quote-photos"><h2>玄関の写真</h2>${data.photos.map((p,i)=>p?`<figure class="quote-photo"><img src="${escape(p.url)}" alt="${i===0?'玄関の正面':'気になる部分'}"><figcaption>${i===0?'正面の写真':'気になる部分'}</figcaption></figure>`:'').join('')}</section>`:''}</article>`;
}
function show(data,values){
 document.getElementById('quote-preview')?.remove();
 const previous=document.activeElement,preview=document.createElement('section');preview.id='quote-preview';preview.setAttribute('role','dialog');preview.setAttribute('aria-modal','true');preview.setAttribute('aria-label','見積もり依頼書のプレビュー');
 const content=paper(data,values);
 preview.innerHTML=`<div class="quote-toolbar"><button class="smallbtn" id="quote-close">← 編集に戻る</button><button class="primary" id="quote-print">印刷・PDF保存</button><button class="smallbtn" id="quote-save">依頼書を保存（HTML）</button><p class="micro">PDFにするには、印刷画面でPDF保存を選びます。保存先の表示は端末により異なります。</p><p id="quote-status" class="micro" role="status"></p></div><style>${paperCSS.replaceAll('body{','.quote-preview-body{').replaceAll('h1{','#quote-preview h1{').replaceAll('h2{','#quote-preview h2{').replaceAll('p{','#quote-preview p{').replaceAll('li{','#quote-preview li{')}</style>${content}`;
 const siblings=[...document.body.children].filter(e=>!['SCRIPT','STYLE'].includes(e.tagName));
 const inert=siblings.map(e=>[e,e.inert]);inert.forEach(([e])=>e.inert=true);
 document.body.append(preview);document.body.classList.add('quote-open');
 function close(){inert.forEach(([e,was])=>e.inert=was);preview.remove();document.body.classList.remove('quote-open');previous?.focus();}
 preview.querySelector('#quote-close').onclick=close;
 preview.onkeydown=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const buttons=[...preview.querySelectorAll('button')],first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};
 preview.querySelector('#quote-print').onclick=async()=>{await Promise.all([...preview.querySelectorAll('img')].map(img=>img.decode().catch(()=>{})));window.print();};
 preview.querySelector('#quote-save').onclick=()=>{
  const html='<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ドアリモ 見積もり依頼書</title><style>'+paperCSS+'</style><body>'+content+'</body></html>';
  const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='ドアリモ見積もり依頼書.html';document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);preview.querySelector('#quote-status').textContent='保存を開始しました。依頼書には入力した連絡先と写真が含まれます。';
 };
 preview.querySelector('#quote-close').focus();
}
function bind(data,values){const el=document.getElementById('quote-form');if(!el)return;el.oninput=()=>Object.assign(values,Object.fromEntries(new FormData(el)));el.onsubmit=e=>{e.preventDefault();Object.assign(values,Object.fromEntries(new FormData(el)));show(data,values);};}
window.DoorimoQuote={form,paper,bind};
})();
